title:              Junglefowl Brazilian Jiu-Jitsu
email:              contact@junglefowlbjj.ca
description:        Martial arts academy in Sackville, New Brunswick. BJJ, MMA, Kickboxing, Yoga, Strength and Conditioning
author:             Evan Brooks
baseurl:            ""
url:                "https://www.junglefowlbjj.ca"

# Social Profiles
pin_location: "https://maps.app.goo.gl/m9oZverv3qeV2Wjp8"
facebook_username:  junglefowlbjj
instagram_username: junglefowlbjj
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-YX5TQVSSXY # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silentlyjung generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-gallery-generator

gallery:
  dir: media # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Media Gallery"    # Title for gallery index page
  title_prefix: "Media Gallery: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  galleries:
    sackville:
      best_image: headline.jpg
      info:
        desc: "A sneak peak into the new gym"
    old_location:
      best_image: headline.jpg
      info:
        desc: "For 3 years we were located in Port Elgin, New Brunswick"
    competitions:
      best_image: headline.png
      info:
        desc: "We have many successful athletes competing in local and international competition"
    kids:
      best_image: headline.jpg
      info:
        desc: "Setting a good example for the next generation of martial artists"
    seminars:
      best_image: headline.jpg
      info:
        desc: "Seminars we have attended around the world"
    boxing:
      best_image: headline.jpg
      info:
        desc: "Boxing classes and fights"
    kickboxing:
      best_image: headline.jpg
      info:
        desc: "Kickboxing classes and fights"
    secret:
      hidden: true          # Don't show this gallery on the index page. People must guess the URL.
